import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { atom, useAtom } from 'jotai';
const jwt = require('jsonwebtoken');

import Head from 'next/head'
import SideBar from "./SideBar";
import Footer from "./Footer";

// create the atom
const userIdAtom = atom('');

const Layout = (props) => {
  const [userId, setUserId] = useAtom(userIdAtom);
  const router = useRouter();

  useEffect(() => {
  const token = localStorage.getItem('token');

    if (token) {
      try {
          const decodedToken = jwt.decode(token);
          const patientId = decodedToken.patientId;
          if (patientId) {
            console.log(`patient ID: ${patientId}`);
            setUserId(patientId);
          } else {
            const therapistId = decodedToken.therapistId
            console.log(`therapist ID: ${therapistId}`);
            setUserId(therapistId);
          }
      } catch (error) {
          console.log('Invalid token', error);
      }
      } else {
          console.log('No token found');
      }
    
  }, [setUserId]);

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (!token) {
    //   router.push('/login');
    console.log('not logged in')
    }
  }, [router]);


    return (
        <>
            <Head>
                <title>Patient Management System</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SideBar />
                <div className=" h-screen bg-gradient-to-tr from-cyan-300 to-blue-300">
                    {props.children}
                </div>
            <Footer />
        </>
    )
}

export default Layout;
export { userIdAtom };