GET http://localhost:3001/patients

###

POST http://localhost:3001/patient/new
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "Surname1",
    "diagnosis": "None"
}

###
DELETE http://localhost:3001/patient/delete/63fa8e36f0e7ba5d901e1325

