GET http://localhost:3001/patient/all

### GET patient by id
GET http://localhost:3001/patient/640270c990b3d644733e1f5b

### GET my patients w/ therapist ID
GET http://localhost:3001/patient/myPatients?therapistId=640252d527c6008a2970e6a9


### GET patient by email
# GET http://localhost:3001/patient/1@2.com
GET http://localhost:3001/patient?email=1@2.com


###

POST http://localhost:3001/patient/new
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "Exercs",
    "diagnosis": "None",
    "exercises": []
}

###
DELETE http://localhost:3001/patient/delete/64026c5890b3d644733e1f3e

###
PUT http://localhost:3001/patient/edit/63faa98891dcdc6e2f013098
Content-Type: application/json

{
    "exerciseId" : "63fb9fa3e1beba9a5f24bb48"
}

### Exercises ###
GET http://localhost:3001/exercise/all

### Get exercise by id
GET http://localhost:3001/exercise/63fbb47b0f9ed3b1e643613f

### Create new exercise

POST http://localhost:3001/exercise/new
Content-Type: application/json

{
    "title": "ex to deleted",
    "description": "this is to be deleted"
}

### Get all the exercises of the Patient w/:id
GET http://localhost:3001/patient/63faa98891dcdc6e2f013098/exercises

### Delete exercise by id
DELETE http://localhost:3001/exercise/63fbb608637e0adc2b5818ff


### Create new therapist
POST http://localhost:3001/therapist/new
Content-Type: application/json

{
    "firstName": "The Best",
    "lastName": "Therapist",
    "occupation": "Physiotherapist"
}

### Get therapists
GET http://localhost:3001/therapist/all

### Get therapist by id
GET http://localhost:3001/therapist/640252d527c6008a2970e6a9


### Update therapist
PUT http://localhost:3001/therapist/edit/63fc0c154641ff9b50083f90
Content-Type: application/json

{
    "patientId" : "63faa98891dcdc6e2f013098"
}

### Delete therapist
DELETE http://localhost:3001/therapist/delete/63fc0c154641ff9b50083f90

### Send add therapist to patient request
POST http://localhost:3001/patient/sendTherapistRequest
Content-Type: application/json

{
    "patientId": "64026e5f90b3d644733e1f50",
    "therapistId": "640252d527c6008a2970e6a9"
}

### Accept therapist to patient request
PUT http://localhost:3001/patient/acceptTherapistRequest
Content-Type: application/json

{
    "patientId": "64026e5f90b3d644733e1f50",
    "therapistId": "640252d527c6008a2970e6a9"
}

### Assign treatment to patient
POST http://localhost:3001/therapist/assignExerciseToPatient
Content-Type: application/json

{
    "patientId": "64026e5f90b3d644733e1f50",
    "therapistId": "640252d527c6008a2970e6a9",
    "exerciseId": "63fb9fa3e1beba9a5f24bb48",
    "repetition": 10,
    "note": "Do it twice a day."
}